# Generated by Django 2.0.7 on 2018-07-12 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('alu_cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
            ],
            options={
                'permissions': (('Estudiante', 'Es Estudiante'), ('Coordinador', 'Es Coordinador'), ('Administrador', 'Es Administrador')),
            },
        ),
        migrations.CreateModel(
            name='Asignatura',
            fields=[
                ('asi_codigo', models.CharField(max_length=7, primary_key=True, serialize=False)),
                ('asi_nombre', models.CharField(max_length=50)),
                ('asi_num_creditos', models.PositiveIntegerField()),
                ('asi_estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asignatura_Docente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asi_doc_estado', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Carrera',
            fields=[
                ('car_codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('car_nombre', models.CharField(max_length=50)),
                ('car_estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cur_paralelo', models.CharField(max_length=5)),
                ('cur_estado', models.BooleanField(default=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('doc_cedula', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('doc_nombres', models.CharField(max_length=50)),
                ('doc_apellidos', models.CharField(max_length=50)),
                ('doc_telefono', models.CharField(max_length=10)),
                ('doc_correo', models.EmailField(max_length=50)),
                ('doc_estado', models.BooleanField(default=True)),
                ('asignaturas', models.ManyToManyField(through='universidad.Asignatura_Docente', to='universidad.Asignatura')),
            ],
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('per_codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('per_nombre', models.CharField(max_length=10)),
                ('per_inicio', models.DateField()),
                ('per_fin', models.DateField()),
                ('per_estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Semestre',
            fields=[
                ('sem_codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('sem_nombre', models.CharField(max_length=15)),
                ('sem_estado', models.BooleanField(default=True)),
                ('carrera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Carrera')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad_Academica',
            fields=[
                ('uni_codigo', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('uni_nombre', models.CharField(max_length=100)),
                ('uni_abreviatura', models.CharField(max_length=10)),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Periodo'),
        ),
        migrations.AddField(
            model_name='curso',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Semestre'),
        ),
        migrations.AddField(
            model_name='carrera',
            name='uni_codigo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Unidad_Academica'),
        ),
        migrations.AddField(
            model_name='asignatura_docente',
            name='docente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Docente'),
        ),
        migrations.AddField(
            model_name='asignatura_docente',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Periodo'),
        ),
        migrations.AddField(
            model_name='asignatura',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Semestre'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Carrera'),
        ),
        migrations.AddField(
            model_name='alumno',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
