# Generated by Django 2.0.7 on 2018-07-12 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'permissions': (('Estudiante', 'Es Estudiante'), ('Coordinador', 'Es Coordinador'))},
        ),
        migrations.AddField(
            model_name='alumno',
            name='alu_observacion',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
