# Generated by Django 2.0.7 on 2018-07-15 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0003_auto_20180714_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semestre',
            name='sem_nombre',
            field=models.CharField(max_length=30),
        ),
    ]
