# Generated by Django 2.0.7 on 2018-07-15 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0004_auto_20180714_2034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='asi_codigo',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
    ]
