# Generated by Django 2.0.7 on 2018-07-15 02:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0005_auto_20180714_2044'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura',
            name='carrera',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='universidad.Carrera'),
        ),
    ]
