# Generated by Django 2.0.7 on 2018-07-15 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0006_asignatura_carrera'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semestre',
            name='carrera',
        ),
    ]
