# Generated by Django 2.0.7 on 2018-07-16 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0007_remove_semestre_carrera'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='per_nombre',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
