# Generated by Django 2.0.7 on 2018-07-17 00:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0009_auto_20180716_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alumno', to='universidad.Alumno'),
        ),
    ]
