# Generated by Django 2.0.7 on 2018-07-17 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0011_auto_20180716_2006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='periodo', to='universidad.Periodo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semestre', to='universidad.Semestre'),
        ),
    ]
