# Generated by Django 2.0.7 on 2018-07-17 01:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0012_auto_20180716_2012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='alumno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Alumno'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Periodo'),
        ),
        migrations.AlterField(
            model_name='curso',
            name='semestre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Semestre'),
        ),
    ]
