# Generated by Django 2.0.7 on 2018-07-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0013_auto_20180716_2029'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docente',
            name='asignaturas',
        ),
        migrations.RemoveField(
            model_name='asignatura_docente',
            name='asignatura',
        ),
        migrations.AddField(
            model_name='asignatura_docente',
            name='asignatura',
            field=models.ManyToManyField(to='universidad.Asignatura'),
        ),
    ]
