# Generated by Django 2.0.7 on 2018-07-18 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0014_auto_20180717_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
