# Generated by Django 2.0.7 on 2018-07-18 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0015_auto_20180717_1903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='periodo',
        ),
    ]
