# Generated by Django 2.0.7 on 2018-07-18 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0017_curso_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asignatura_docente',
            name='periodo',
        ),
    ]
