# Generated by Django 2.0.7 on 2018-07-18 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0019_asignatura_docente_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='asignatura_docente',
            name='asi_doc_eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
