# Generated by Django 2.0.7 on 2018-07-18 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0022_curso_alumno'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='alu_estado',
            field=models.BooleanField(default=True),
        ),
    ]
