# Generated by Django 2.0.7 on 2018-07-19 20:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0023_alumno_alu_estado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together={('semestre', 'periodo', 'cur_paralelo')},
        ),
    ]
