# Generated by Django 2.0.7 on 2018-07-19 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0024_auto_20180719_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='cur_eliminado',
            field=models.BooleanField(default=False),
        ),
    ]
