# Generated by Django 2.0.7 on 2018-07-19 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0025_curso_cur_eliminado'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='curso',
            unique_together=set(),
        ),
    ]
