# Generated by Django 2.0.7 on 2018-08-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0026_auto_20180719_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asignatura',
            name='asi_nombre',
            field=models.CharField(max_length=50),
        ),
    ]
