# Generated by Django 2.0.7 on 2018-08-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0027_auto_20180810_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrera',
            name='car_nombre',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
