# Generated by Django 2.0.7 on 2018-07-12 02:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensaje',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('men_asunto', models.CharField(blank=True, max_length=50, null=True)),
                ('men_mensaje', models.CharField(max_length=200)),
                ('men_fecha', models.DateTimeField(auto_now_add=True)),
                ('men_leido', models.BooleanField(default=False)),
                ('men_estado', models.BooleanField(default=True)),
                ('usuario_destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinatario', to=settings.AUTH_USER_MODEL)),
                ('usuario_remitente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remitente', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Notificaciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('not_notificacion', models.CharField(max_length=100)),
                ('not_fecha', models.DateTimeField(auto_now_add=True)),
                ('not_leido', models.BooleanField(default=False)),
                ('not_estado', models.BooleanField(default=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
