# Generated by Django 2.0.7 on 2018-07-12 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universidad', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hor_paralelo', models.CharField(max_length=5)),
                ('hor_dia', models.CharField(max_length=15)),
                ('hor_horas', models.PositiveIntegerField()),
                ('hor_estado', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Docente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Periodo')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Semestre')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seg_paralelo', models.CharField(max_length=5)),
                ('seg_porcentaje_real', models.PositiveIntegerField()),
                ('seg_porcentaje_ideal', models.PositiveIntegerField()),
                ('seg_observaciones', models.CharField(blank=True, max_length=100, null=True)),
                ('seg_semana', models.CharField(max_length=20)),
                ('seg_mes', models.CharField(max_length=20)),
                ('seg_fecha', models.DateField()),
                ('seg_estado', models.BooleanField(default=True)),
                ('asignatura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Asignatura')),
                ('docente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Docente')),
                ('periodo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Periodo')),
                ('semestre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Semestre')),
            ],
        ),
    ]
