# Generated by Django 2.0.7 on 2018-07-22 02:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='periodo',
        ),
    ]
