# Generated by Django 2.0.7 on 2018-07-22 02:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0003_seguimiento_periodo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='periodo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='universidad.Periodo'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_observaciones',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
