# Generated by Django 2.0.7 on 2018-07-22 04:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0026_auto_20180719_1629'),
        ('seguimiento', '0004_auto_20180721_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='seguimiento',
            unique_together={('seg_fecha', 'asignatura')},
        ),
    ]
