# Generated by Django 2.0.7 on 2018-07-22 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0005_auto_20180721_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_observaciones',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
