# Generated by Django 2.0.7 on 2018-07-24 00:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0006_auto_20180722_0027'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='horario',
            name='periodo',
        ),
    ]
