# Generated by Django 2.0.7 on 2018-07-24 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0026_auto_20180719_1629'),
        ('seguimiento', '0007_remove_horario_periodo'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Periodo'),
        ),
    ]
