# Generated by Django 2.0.7 on 2018-07-26 02:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0008_horario_periodo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seguimiento',
            name='seg_mes',
        ),
        migrations.AlterField(
            model_name='horario',
            name='periodo',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='universidad.Periodo'),
        ),
    ]
