# Generated by Django 2.0.7 on 2018-07-27 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0009_auto_20180725_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_porcentaje_ideal',
            field=models.FloatField(),
        ),
    ]
