# Generated by Django 2.0.7 on 2018-07-27 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0011_auto_20180727_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_porcentaje_real',
            field=models.FloatField(),
        ),
    ]
