# Generated by Django 2.0.7 on 2018-07-27 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguimiento', '0012_auto_20180727_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_porcentaje_ideal',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='seg_porcentaje_real',
            field=models.DecimalField(decimal_places=2, max_digits=3),
        ),
    ]
