# Generated by Django 2.0.7 on 2018-08-10 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0027_auto_20180810_1015'),
        ('seguimiento', '0014_auto_20180727_1741'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='seguimiento',
            unique_together={('seg_fecha', 'asignatura', 'seg_semana')},
        ),
    ]
