# Generated by Django 2.0.7 on 2018-08-28 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0028_auto_20180814_2054'),
        ('seguimiento', '0015_auto_20180810_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Carrera'),
        ),
        migrations.AddField(
            model_name='seguimiento',
            name='carrera',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universidad.Carrera'),
        ),
    ]
