# Generated by Django 2.0.7 on 2018-09-03 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('universidad', '0028_auto_20180814_2054'),
        ('seguimiento', '0016_auto_20180828_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='seguimiento',
            name='seg_validado',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterUniqueTogether(
            name='seguimiento',
            unique_together={('seg_fecha', 'asignatura', 'seg_semana', 'carrera')},
        ),
    ]
